// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetConfigError, GetConfigResponse } from './types.gen';

export const client = createClient(createConfig());

export class TinyMceService {
    public static getConfig<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
        return (options?.client ?? client).get<GetConfigResponse, GetConfigError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/tiny-mce/config'
        });
    }
    
}