// This file is auto-generated by @hey-api/openapi-ts

export type ProblemDetails = {
    type?: (string) | null;
    title?: (string) | null;
    status?: (number) | null;
    detail?: (string) | null;
    instance?: (string) | null;
    [key: string]: (unknown | string | number) | undefined;
};

export type RichTextEditorCommand = {
    alias: string;
    name: string;
    mode: RichTextEditorCommandModeModel;
};

export type RichTextEditorCommandModeModel = 'Insert' | 'Selection' | 'All';

export type RichTextEditorSettings = {
    commands: Array<(RichTextEditorCommand)>;
    plugins: Array<(string)>;
    customConfig: {
        [key: string]: (string);
    };
    validElements: string;
    invalidElements: string;
    cloudApiKey?: (string) | null;
};

export type TinyMceConfigResponseModel = {
    richTextEditor?: ((RichTextEditorSettings) | null);
    config?: ((TinyMceSettings) | null);
};

export type TinyMceSettings = {
    apikey: string;
    openAiApikey: string;
    pluginsToExclude: Array<(string)>;
    customConfig: {
        [key: string]: unknown;
    };
};

export type GetConfigResponse = ((TinyMceConfigResponseModel));

export type GetConfigError = (unknown | (ProblemDetails));