// This file is auto-generated by @hey-api/openapi-ts

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | (string | null) | (string | null) | (number | null) | (string | null) | (string | null) | undefined;
};

export type RichTextEditorCommand = {
    alias: string;
    name: string;
    mode: RichTextEditorCommandModeModel;
};

export enum RichTextEditorCommandModeModel {
    INSERT = 'Insert',
    SELECTION = 'Selection',
    ALL = 'All'
}

export type RichTextEditorSettings = {
    commands: Array<RichTextEditorCommand>;
    plugins: Array<string>;
    customConfig: {
        [key: string]: string;
    };
    validElements: string;
    invalidElements: string;
    cloudApiKey?: string | null;
};

export type TinyMceConfigResponseModel = {
    richTextEditor?: RichTextEditorSettings | null;
    config?: TinyMceSettings | null;
};

export type TinyMceSettings = {
		apikey: string;
		tinyMceVersion: string;
		tinyMceUrl: string;
    openAiApikey: string;
    pluginsToExclude: Array<string>;
    customConfig: {};
};

export type GetConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/tiny-mce/config';
};

export type GetConfigErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetConfigError = GetConfigErrors[keyof GetConfigErrors];

export type GetConfigResponses = {
    /**
     * OK
     */
    200: TinyMceConfigResponseModel;
};

export type GetConfigResponse = GetConfigResponses[keyof GetConfigResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44308' | (string & {});
};
