export const manifests: Array<UmbExtensionManifest> = [
	{
		type: 'localization',
		name: 'TinyMCE Umbraco English Localization',
		alias: 'Umb.TinyMCE.Localization.English',
		js: () => import('./en.js'),
		meta: { culture: 'en' },
	},
	{
		type: 'localization',
		name: 'TinyMCE Umbraco Arabic Localization',
		alias: 'Umb.TinyMCE.Localization.Arabic',
		weight: -100,
		meta: { culture: 'ar' },
		js: () => import('./ar.js'),
	},
	{
		type: 'localization',
		name: 'TinyMCE Umbraco Bosnian Localization',
		alias: 'Umb.TinyMCE.Localization.Bosnian',
		weight: -100,
		meta: { culture: 'bs' },
		js: () => import('./bs.js'),
	},
	{
		type: 'localization',
		name: 'TinyMCE Umbraco Czech Localization',
		alias: 'Umb.TinyMCE.Localization.Czech',
		weight: -100,
		meta: { culture: 'cs-cz' },
		js: () => import('./cs.js'),
	},
	{
		type: 'localization',
		name: 'TinyMCE Umbraco Welsh Localization',
		alias: 'Umb.TinyMCE.Localization.Cy-GB',
		weight: -100,
		meta: { culture: 'cy' },
		js: () => import('./cy.js'),
	},
	{
		type: 'localization',
		name: 'TinyMCE Umbraco Danish Localization',
		alias: 'Umb.TinyMCE.Localization.Da_DK',
		weight: -100,
		meta: { culture: 'da' },
		js: () => import('./da.js'),
	},
	{
		type: 'localization',
		name: 'TinyMCE Umbraco German Localization',
		alias: 'Umb.TinyMCE.Localization.German',
		weight: -100,
		meta: { culture: 'de' },
		js: () => import('./de.js'),
	},
	{
		type: 'localization',
		name: 'TinyMCE Umbraco French Localization',
		alias: 'Umb.TinyMCE.Localization.French',
		weight: -100,
		meta: { culture: 'fr' },
		js: () => import('./fr.js'),
	},
	{
		type: 'localization',
		name: 'TinyMCE Umbraco Croatian Localization',
		alias: 'Umb.TinyMCE.Localization.Croatian',
		weight: -100,
		meta: { culture: 'hr', },
		js: () => import('./hr.js'),
	},
	{
		type: 'localization',
		name: 'TinyMCE Umbraco Italian Localization',
		alias: 'Umb.TinyMCE.Localization.Italian',
		weight: -100,
		meta: { culture: 'it' },
		js: () => import('./it.js'),
	},
	{
		type: 'localization',
		name: 'TinyMCE Umbraco Dutch Localization',
		alias: 'Umb.TinyMCE.Localization.Dutch',
		weight: -100,
		meta: { culture: 'nl' },
		js: () => import('./nl.js'),
	},
	{
		type: 'localization',
		name: 'TinyMCE Umbraco Turkish Localization',
		alias: 'Umb.TinyMCE.Localization.Turkish',
		weight: -100,
		meta: { culture: 'tr' },
		js: () => import('./tr.js'),
	},
];
